### ISSUE TITLE
Change name to rubyconf

### ISSUE THREAD

**Issue by itsmrwave** [nairuby/ruby-conf-ke#1]
Wondering if we could change the naming from `ruby-conf-ke` to just `rubyconf`. So that we get something like this (examples) ...

* http://rubyconf.nairuby.org/2015/
* http://rubyconf.nairuby.org/2016/
* http://rubyconf.nairuby.org/2017/
* http://rubyconf.nairuby.org/2018/

This looks way better than `http://ruby-conf-ke.nairuby.org`. Also, I think we shouldn't explicitly say `ke`, who know what might happen in the future.

Ps: Not sure how possible this is since we are using Foreman (never used it).

cc @Banta

**Comment by itsmrwave** [comment]
Also ... we could have had this at [nairuby.org](http://nairuby.org). For example .... http://nairuby.org/conferences/ so that over time we have ...

* http://nairuby.org/conferences/2015/
* http://nairuby.org/conferences/2016/
* http://nairuby.org/conferences/2017/
* http://nairuby.org/conferences/2018/

They would/could have their own layouts and don't have to look the same as the rest of the site. Just depends on how we organise everything.

**Comment by Banta** [comment]
We can start with the first one. For the second one we'll need to merge it with nairuby.org site.

**Comment by Banta** [comment]
I've added rubyconf subdomain. It'll be active in a few hours.

**Comment by itsmrwave** [comment]
Super :+1:  That's fine with me.

About the nairuby.org site ... I agree with that too as that requires significant effort and we kinda have a site up already. When the time comes, I can help in porting it.

**Comment by itsmrwave** [comment]
@Banta Domain seems like it's active now. You might need to update the configuration on Heroku though ... for [rubyconf.nairuby.org](http://rubyconf.nairuby.org).

**Comment by Banta** [comment]
Hi @itsmrwave I could not add that domain in heroku. It seems like that domain is taken. I'll try a redirect from the domain host.

**Comment by itsmrwave** [comment]
Sawa :+1:
